import type { Metadata } from "next";
import { Inter, Pixelify_Sans, Tiny5 } from "next/font/google";
import "./globals.css";
import GoldDustBackground from "./components/GoldDustBackground";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontBody = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-body",
  display: "swap",
});

const fontPixel = Pixelify_Sans({
  subsets: ["latin", "cyrillic"],
  variable: "--font-pixel",
  display: "swap",
});

const tiny5 = Tiny5({
  weight: "400",
  subsets: ["latin", "cyrillic"],
  variable: "--font-title",
  display: "swap",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" className={`${fontBody.variable} ${fontPixel.variable} ${tiny5.variable}`}>
      <body className="font-body antialiased">
        <GoldDustBackground />
        <div className="relative z-10">{children}</div>
      </body>
    </html>
  );
}
